### ISSUE TITLE
User Story 3: As a player I can view my profile page, game history and aggregate results so that ...

### ISSUE THREAD

**Issue by jwyatt1999** [jwyatt1999/CITS3403_Cartographers#4]
- [x] Create visual representation of the database schema, 1 day
- [x] Implement score tracking per account (writing to the database), 2 days
- [x] Implement statistics page, which reads and displays data from database, seasons, options for what to display, 2 days
- [x] Extend profile page to include new functionalities - average points in daily/freeplay/overall, total games completed in daily/freeplay/overall, highest score in daily/freeplay/overall, 1 day

Total: 6 days

**Comment by Bsubs** [comment]
Implemented database and per profile tracking as well as leaderboard page in PR: #22

**Comment by Bsubs** [comment]
Implemented in PR: #27
