### ISSUE TITLE
User Story 4: As a player I can view the leaderboard which has my data and data from other players so that ...

### ISSUE THREAD

**Issue by jwyatt1999** [jwyatt1999/CITS3403_Cartographers#5]
- [x] Implement leaderboard page, "daily, and freeplay" tabs, freeplay takes top 10 scores ever in freeplay mode and also tells the user their top placement on the leaderboard (which can be higher than 10th place), daily takes top 10 scores sorted by date and the user can select which date they want to see from the past 14 days and it will show the placement of the user on that leaderboard (which again can be higher than 10th place or N/A if they didn't completed that daily)

**Comment by Bsubs** [comment]
Implemented in PR: #27
