### ISSUE TITLE
User Story 6: As a player I can navigate to the majority of features from the main page and can efficiently navigate between pages so that ...

### ISSUE THREAD

**Issue by jwyatt1999** [jwyatt1999/CITS3403_Cartographers#7]
- [x] Implement main page and skeleton pages for other pages, 0.5 days
- [x] Ensure page hierarchy is shallow and inter-page navigation is implemented where it makes sense to do so, 0.5 days

Total: 1 day

**Comment by Bsubs** [comment]
Implemented skeleton structure in #15
